vim.cmd('source ~/.config/nvim/plugins.vim')
require('cmp_config')
require('lsp_config')
require('lualine_config')
require('treesitter_config')
require('go-move')
require('marks_config')
require('luasnip_config')
require('dashboard_config')
vim.cmd('source ~/.config/nvim/settings.vim')
vim.cmd('source ~/.config/nvim/misc/keybinds.vim')
vim.cmd('source ~/.config/nvim/misc/autocommands.vim')
vim.cmd('source ~/.config/nvim/misc/functions.vim')
