require('impatient')
require('plugins')
require('settings')
require('mappings')
--love the spaghetti
require('config/lualine')
require('config/misc')
require('config/gitsigns')
require('config/telescope')
require('config/treesitter')
require('config/lsp')
require('config/cmp')
require('config/gomove')
require('config/alpha')
require('config/nvterm')
require('config/luasnip')
require('config/todo')
