#!/bin/sh
setxkbmap pt
xrdb merge ~/.Xresources &
/usr/lib/mate-polkit/polkit-mate-authentication-agent-1 &
pcloud &
deadd-notification-center & 
doas /bin/acpid -f &
# run bar script and dwm ( never remove this )
picom --experimental-backends &
dbus-launch --exit-with-session dwm
