#!/bin/sh
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx
export GLFW_IM_MODULE=ibus
export SDL_IM_MODULE=fcitx
export QT_QPA_PLATFORMTHEME="kvantum"
QT_XCB_TABLET_LEGACY_COORDINATES=1

pcloud1 &
polkit-mate &
fcitx5 &
