#/usr/share/portage/config/make.conf for more
#
#
#USE flags, pretty self explanatory, probably will be done automatically when gentoo is actually installed idk
USE="-systemd -emacs -kde dist-kernel nvidia X acpi alsa libnotify lm-sensors networkmanager policykit pulseaudio pipewire udev"
#define host obviously, x86 linux
CHOST="x86_64-pc-linux-gnu"
#set C, C++ flags, it's a 5600H ryzen
COMMON_FLAGS="-O2 -march=native -pipe"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"
#EMERGE OPTS
EMERGE_DEFAULT_OPTS="--jobs=8 --load-average=7"
# Advanced Masking, dont think is needed so ignoring, putting architecture
ACCEPT_KEYWORDS="~amd64"
# ACCEPT_LICENSE, not a schizo so
# Portage Directories, dfault is probably fine 
# Fetching files, dont need proxies,wget is fine
#changed mirrors using the site, the originals are here for fallback
GENTOO_MIRRORS="https://ftp.rn.tecnico.ulisboa.pt/pub/gentoo/gentoo-distfile https://ftp.rnl.tecnico.ulisboa.pt/pub/gentoo/gentoo-distfile ftp://ftp.rnl.tecnico.ulisboa.pt/pub/gentoo/gentoo-distfiles rsync://ftp.rnl.ulsiboa.pt/pub/gentoo/gentoo-distfiles ftp://ftp.dei.uc.pt/pub/linux/gentoo http://ftp.dei.uc.pt/pub/linux/gentoo"
# Synchronizing Portage
#Put euro mirror here 
# SYNC="rsync://rsync.europe.gentoo.org/gentoo-portage"
#So it retries till all addresses are gone
# PORTAGE_RSYNC_RETRIES="-1"
#might put --ask or --verbose here later idk
#EMERGE_DEFAULT_OPTS=""
#Make is good for faster compilng so upping it to cpus +1 (7) 
MAKEOPTS="-j7"
#AUTOCLEAN seems good so not having many packages overlaping
AUTOCLEAN="yes"
# FEATURES dont think i need to change
# logging related variables:seems useful so
# PORTAGE_ELOG_CLASSES: selects messages to be logged, possible values are:
#                          info, warn, error, log, qa, *
PORTAGE_ELOG_CLASSES="log warn error"
# PORTAGE_ELOG_SYSTEM: seems useful again so 
PORTAGE_ELOG_SYSTEM="save_summary:log,warn,error,qa echo"
#PORTAGE_ELOG_COMMAND: wont do logging wizardry so
# PORTAGE_ELOG_MAILURI: mail? pfft poor sys admins
# oh cool im done
ACCEPT_LICENSE="*"
GRUB_PLATFORMS="efi-64"
LC_MESSAGES=C
POSTDIR="/var/db/repos/gentoo"
DISTDIR="/var/cache/distfiles"
PKGDIR="/var/cache/binpkgs"
